version: '3.9'

services:
    mongo:
        container_name: mongo_container
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=arvrlab
            - MONGO_INITDB_DATABASE=pdfsearch
        networks: 
            - arvr
        volumes:
            - mongodb-data:/data/db
        ports: 
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=arvrlab
            - ME_CONFIG_MONGODB_URL=mongodb://root:arvrlab@mongo:27017/
        networks: 
            - arvr
        depends_on:
            - mongo
        
networks:
    arvr:
        name: arvr-net

volumes:
    mongodb-data: